#!/bin/bash

#docker build -t erdayegauss/bonus:latest  .
OSTYPE=`uname -m`

function cleanup ()
    {


      CONTAINER_IDS=$(docker ps | grep "dev\|bonus\|peer\|example\|mysql\|ca_peer" | awk '{print $1}')
echo
      if [ -z "$CONTAINER_IDS" -o "$CONTAINER_IDS" = " " ]; then
              echo "========== No containers available for deletion =========="
      else
#              docker rm -f $CONTAINER_IDS
              docker rm -f $(docker ps -qa)
      fi
echo


      DOCKER_IMAGE_IDS=$(docker images | grep "bonus\|dev" | awk '{print $3}')
      echo
      if [ -z "$DOCKER_IMAGE_IDS" -o "$DOCKER_IMAGE_IDS" = " " ]; then
              echo "========== No images available for deletion ==========="
      else
              docker rmi -f $DOCKER_IMAGE_IDS
      fi
      echo

    }


cleanup

docker volume create mysql-db

if [[ "$OSTYPE" == "s390x" ]]; then

  docker-compose -f docker-compose390.yml up -d

sleep 10s

docker exec -it mysql bash -c 'mysql -uroot  < docker-entrypoint-initdb.d/bonuspointsexchange.sql'

else

  docker-compose up -d

fi
